// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBP5vxsl1XBWQ6A-_hipwDhtQ3fwm3Viw',
    appId: '1:283851340071:web:8a19ffa4c43a2b491c5102',
    messagingSenderId: '283851340071',
    projectId: 'ahara-gsc',
    authDomain: 'ahara-gsc.firebaseapp.com',
    storageBucket: 'ahara-gsc.appspot.com',
    measurementId: 'G-FXNJ5PSH7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDepBb5EilBKjl8FBUSifoXtqpNI8py2EU',
    appId: '1:283851340071:android:fc288b0d89bd72531c5102',
    messagingSenderId: '283851340071',
    projectId: 'ahara-gsc',
    storageBucket: 'ahara-gsc.appspot.com',
  );
}
